export const ADD_BASKET = 'ADD_BASKET';
export const ADD_BASKET_SUCCESS = 'ADD_BASKET_SUCCESS';
export const ADD_BASKET_ERROR = 'ADD_BASKET_ERROR';

export const GET_ITEM_REMOVE = 'GET_ITEM_REMOVE';
export const ITEM_REMOVE_SUCCESS = 'ITEM_REMOVE_SUCCESS';
export const ITEM_REMOVE_ERROR = 'ITEM_REMOVE_ERROR';

export const SET_USER = 'SET_USER';

export const EMPTY_BASKET = 'EMPTY_BASKET';

export const SET_SHIPPING_DATA = 'SET_SHIPPING_DATA';
export const SET_SHIPPING_MESSAGE= 'SET_SHIPPING_MESSAGE';